# https://practical.li/clojure/continuous-integration/github-actions/
# <3 practicalli

name: Test

on:
  # run it on push
  push:
  # run it during pull request
  pull_request:

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Clojure Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: cache-${{ hashFiles('**/deps.edn') }}

      - name: Prepare java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1208

      - name: Run Unit tests
        run: ./script/kaocha
